- name: HOST PREPARATION
  hosts: localhost
  connection: local
  roles:
    - ansible-role-host-preparation
  become_user: root

- name: SSHD SERVICE RESTART (for Amazon Linux)
  hosts: all
  user: ec2-user
  tasks:
    - name: Restarting sshd
      shell: sudo /etc/init.d/sshd restart
  when: "{{ IS_AMAZON_LINUX }}"

- name: NTP INSTALLATION
  hosts: all
  roles:
    - ansible-role-ntp
  become_user: root

- name: CLEANING UP THE HOST
  hosts: localhost
  connection: local
  become_user: root
  tasks:
    - name: Removing generated SSH key from the Hosts 'authorized_key' file
      lineinfile: dest=/rootfs/root/.ssh/authorized_keys state=absent regexp='.*Ansible@docker'

- name: SSHD SERVICE RESTART (for Amazon Linux)
  hosts: all
  user: ec2-user
  tasks:
    - name: Restarting sshd
      shell: sudo /etc/init.d/sshd restart
  when: "{{ IS_AMAZON_LINUX }}"

- name: REMOVING EC2-USER KEY (for Amazon Linux)
  hosts: localhost
  connection: local
  become_user: root
  tasks:
    - name: Removing generated SSH key from the ec2-user Hosts 'authorized_key' file
      lineinfile: dest=/rootfs/home/ec2-user/.ssh/authorized_keys state=absent regexp='.*Ansible@docker'
  when: "{{IS_AMAZON_LINUX}}"
