- name: HOST PREPARATION
  hosts: localhost
  connection: local
  roles:
    - ansible-role-host-preparation
  become_user: root

- name: NTP INSTALLATION
  hosts: all
  roles:
    - ansible-role-ntp
  user: "{{ HOST_USER }}"
  become: true
  become_user: root

- name: CLEANING UP THE HOST
  hosts: localhost
  connection: local
  become_user: root
  tasks:
    - name: Removing generated SSH key from the Hosts 'authorized_key' file
      lineinfile: dest=/rootfs/home/{{ HOST_USER }}/.ssh/authorized_keys state=absent regexp='.*Ansible@docker'
