---
- name: Generating temporary SSH key
  shell: ssh-keygen -b 4096 -t rsa -f /root/.ssh/id_rsa -q -N "" -C "Ansible@docker"
  args:
    creates: /root/.ssh/id_rsa

- name: Adding generated SSH key to the Hosts user 'authorized_key' file
  lineinfile:
    dest: /rootfs/home/"{{ host_user }}"/.ssh/authorized_keys
    state: present
    regexp: '.*Ansible@docker'
    line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
