---
- name: Check whether /etc/ssh/sshd_config contains "#PermitRootLogin yes" (ssh login disabled for root user)
  command: grep -Fxq "#PermitRootLogin yes" /rootfs/etc/ssh/sshd_config
  register: sshd_enabled
  check_mode: no
  ignore_errors: True
  changed_when: False

- name: Generating temporary SSH key for root user
  shell: ssh-keygen -b 4096 -t rsa -f /root/.ssh/id_rsa -q -N "" -C "Ansible@docker"
  args:
    creates: /root/.ssh/id_rsa

- name: Adding generated SSH key to the Hosts root user 'authorized_key' file
  lineinfile:
    dest: /rootfs/root/.ssh/authorized_keys
    state: present
    regexp: '.*Ansible@docker'
    line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  
  - name: Enabling ssh login for root user
    replace: dest=/rootfs/etc/ssh/sshd_config regexp='#PermitRootLogin yes' replace='PermitRootLogin yes'
    when: sshd_enabled.rc == 0 and "{{IS_AMAZON_LINUX}}"

- block:
    - name: Generating temporary SSH key for the home user
      shell: ssh-keygen -b 4096 -t rsa -f /root/.ssh/id_rsa -q -N "" -C "Ansible@docker"
      args:
        creates: /root/.ssh/id_rsa
    - name: Adding generated SSH key to the Hosts 'authorized_key' file
      lineinfile: 
        dest: /rootfs/home/ec2-user/.ssh/authorized_keys 
        state: present 
        regexp: '.*Ansible@docker' 
        line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  when: "{{IS_AMAZON_LINUX}}"